apiVersion: agones.dev/v1
kind: GameServer

metadata:
  name: minesweeper
  namespace: emortalmc

spec:
  template:
    spec:
      containers:
        - name: minesweeper
          image: emortalmc/minesweeper:dev
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
  ports:
    - name: default
      portPolicy: Dynamic
      containerPort: 25565
      protocol: TCP
  health:
    initialDelaySeconds: 5
    periodSeconds: 15
    failureThreshold: 2
